const c4TypeExpectations = {
  "c4-context": new Set(["actor", "client", "service", "deployment-unit", "external-service", "software-system", "trust-boundary"]),
  "c4-container": new Set(["actor", "client", "service", "worker", "data-store", "queue", "deployment-unit", "external-service", "software-system"]),
  "c4-component": new Set(["actor", "client", "service", "module", "worker", "data-store", "queue", "external-service"])
};

const c4DensityBudgets = {
  "c4-context": { nodes: 14, relationships: 18 },
  "c4-container": { nodes: 14, relationships: 24 },
  "c4-component": { nodes: 14, relationships: 28 }
};

function viewNodeIds(view) {
  return view.lanes.flatMap((lane) => lane.nodeIds);
}

function uniqueId(base, usedIds) {
  let candidate = base;
  let index = 2;
  while (usedIds.has(candidate)) {
    candidate = `${base}-${index}`;
    index += 1;
  }
  usedIds.add(candidate);
  return candidate;
}

function structuralRelationshipCount(view, nodeMap) {
  const visible = new Set(viewNodeIds(view));
  let count = 0;
  for (const nodeId of visible) {
    const node = nodeMap.get(nodeId);
    for (const dependencyId of node?.dependencies ?? []) {
      if (visible.has(dependencyId)) count += 1;
    }
  }
  return count;
}

function duplicateViewNodes(view) {
  const counts = new Map();
  for (const nodeId of viewNodeIds(view)) counts.set(nodeId, (counts.get(nodeId) ?? 0) + 1);
  return [...counts].filter(([, count]) => count > 1).map(([nodeId]) => nodeId);
}

function dedupeC4View(view) {
  const seen = new Set();
  let removed = 0;
  const lanes = view.lanes.map((lane) => {
    const nodeIds = [];
    for (const nodeId of lane.nodeIds) {
      if (seen.has(nodeId)) {
        removed += 1;
        continue;
      }
      seen.add(nodeId);
      nodeIds.push(nodeId);
    }
    return { ...lane, nodeIds };
  });
  return { view: { ...view, lanes }, removed };
}

function connectedToFocus(nodeId, focusIds, nodeMap) {
  const node = nodeMap.get(nodeId);
  if ([...(node?.dependencies ?? [])].some((dependencyId) => focusIds.has(dependencyId))) return true;
  for (const focusId of focusIds) {
    if ((nodeMap.get(focusId)?.dependencies ?? []).includes(nodeId)) return true;
  }
  return false;
}

function viewWithIds(view, nodeIds) {
  const selected = new Set(nodeIds);
  return {
    ...view,
    lanes: view.lanes
      .map((lane) => ({ ...lane, nodeIds: lane.nodeIds.filter((nodeId) => selected.has(nodeId)) }))
      .filter((lane) => lane.nodeIds.length > 0)
  };
}

function splitDenseC4View(view, nodeMap, usedViewIds) {
  const budget = c4DensityBudgets[view.type];
  if (!budget || view.lanes.length < 2) return [];

  const splits = [];
  for (const focusLane of view.lanes) {
    if (!focusLane.nodeIds.length) continue;
    const selected = new Set(focusLane.nodeIds.slice(0, budget.nodes));
    const focusIds = new Set(selected);
    const candidates = view.lanes
      .filter((lane) => lane.id !== focusLane.id)
      .flatMap((lane) => lane.nodeIds)
      .filter((nodeId) => connectedToFocus(nodeId, focusIds, nodeMap));

    for (const candidate of candidates) {
      if (selected.has(candidate) || selected.size >= budget.nodes) continue;
      const trial = viewWithIds(view, [...selected, candidate]);
      if (structuralRelationshipCount(trial, nodeMap) <= budget.relationships) selected.add(candidate);
    }

    const id = uniqueId(`${view.id}-${focusLane.id}`, usedViewIds);
    splits.push({
      ...viewWithIds(view, selected),
      id,
      name: `${view.name}: ${focusLane.name}`,
      summary: `${view.summary} Focused on ${focusLane.name}; generated by architext sync without changing architecture facts.`
    });
  }

  return splits.length > 1 ? splits : [];
}

export function c4IssuesForView(view, nodeMap) {
  const issues = [];
  const allowedTypes = c4TypeExpectations[view.type];
  const budget = c4DensityBudgets[view.type];
  const duplicates = duplicateViewNodes(view);
  if (duplicates.length) issues.push(`${view.id}: duplicate node membership: ${duplicates.join(", ")}`);
  if (!allowedTypes) issues.push(`${view.id}: unsupported C4 view type ${view.type}`);
  for (const nodeId of viewNodeIds(view)) {
    const node = nodeMap.get(nodeId);
    if (!node) issues.push(`${view.id}: missing node ${nodeId}`);
    else if (allowedTypes && !allowedTypes.has(node.type)) issues.push(`${view.id}: ${nodeId} has ${node.type}, which does not belong in ${view.type}`);
  }
  if (budget) {
    const nodeCount = new Set(viewNodeIds(view)).size;
    const relationshipCount = structuralRelationshipCount(view, nodeMap);
    if (nodeCount > budget.nodes) issues.push(`${view.id}: ${nodeCount} nodes exceeds ${budget.nodes}; split the view`);
    if (relationshipCount > budget.relationships) issues.push(`${view.id}: ${relationshipCount} relationships exceeds ${budget.relationships}; split the view`);
  }
  return issues;
}

export function repairC4Views(views, nodeMap) {
  const usedViewIds = new Set(views.map((view) => view.id));
  const nextViews = [];
  const changes = [];

  for (const view of views) {
    if (!view.type?.startsWith("c4-")) {
      nextViews.push(view);
      continue;
    }

    const beforeDuplicates = duplicateViewNodes(view);
    const deduped = dedupeC4View(view);
    if (deduped.removed) changes.push(`${view.id}: remove ${deduped.removed} duplicate node membership entr${deduped.removed === 1 ? "y" : "ies"} (${beforeDuplicates.join(", ")})`);

    const budget = c4DensityBudgets[deduped.view.type];
    const nodeCount = new Set(viewNodeIds(deduped.view)).size;
    const relationshipCount = structuralRelationshipCount(deduped.view, nodeMap);
    if (budget && (nodeCount > budget.nodes || relationshipCount > budget.relationships)) {
      const splits = splitDenseC4View(deduped.view, nodeMap, usedViewIds);
      if (splits.length) {
        changes.push(`${view.id}: split dense ${deduped.view.type} view into ${splits.length} scoped views`);
        nextViews.push(...splits);
        continue;
      }
    }

    nextViews.push(deduped.view);
  }

  return { views: nextViews, changes };
}
