//! Data Model mode: the Schema projection of `entities.json`, drawn as SVG.
//!
//! Real SVG rather than a canvas, so the text stays selectable, CSS theming
//! applies, and the browser's own print path (which is what the PDF button
//! drives) renders the diagram as page content.

use leptos::*;

use architext_routing::model::Point;
use architext_routing::plan_er::{
    plan_er, ErBox, ErEdge, ErFoot, ErPlan, BOX_PAD_Y, HEADER_H, ROW_H,
};

use crate::data_model_view_model::{fk_annotation, key_glyph, to_er_input, Projection};
use crate::state::use_app_state;

/// Length of the tick/prong drawn at an edge endpoint.
const FOOT_LEN: f64 = 9.0;
/// Half-height of the crow's-foot spread.
const FOOT_SPREAD: f64 = 5.0;

#[component]
pub fn DataModelPanel() -> impl IntoView {
    let state = use_app_state();
    let (projection, set_projection) = create_signal(Projection::Schema);

    let doc = move || state.data.get().entities.as_ref().and_then(|r| r.as_ref().ok().cloned());
    let error =
        move || state.data.get().entities.as_ref().and_then(|r| r.as_ref().err().map(|e| e.to_string()));

    view! {
        <div class="data-model-panel">
            <div class="data-model-panel__projections" role="tablist" aria-label="Projection">
                {Projection::ALL
                    .iter()
                    .map(|p| {
                        let p = *p;
                        view! {
                            <button
                                class="data-model-panel__projection"
                                class:is-active=move || projection.get() == p
                                role="tab"
                                disabled=!p.available()
                                title=p.unavailable_reason().unwrap_or("")
                                aria-selected=move || (projection.get() == p).to_string()
                                on:click=move |_| {
                                    if p.available() {
                                        set_projection.set(p);
                                    }
                                }
                            >
                                {p.label()}
                            </button>
                        }
                    })
                    .collect_view()}
            </div>

            {move || {
                if let Some(err) = error() {
                    return view! {
                        <div class="data-model-panel__empty">
                            <span class="overline">"DATA MODEL"</span>
                            <p>{err}</p>
                        </div>
                    }
                        .into_view();
                }
                match doc() {
                    None => view! { <DataModelEmptyState/> }.into_view(),
                    Some(d) if d.entities.is_empty() => {
                        view! { <DataModelEmptyState/> }.into_view()
                    }
                    Some(d) => {
                        let plan = plan_er(&to_er_input(&d));
                        view! { <ErDiagram plan=plan/> }.into_view()
                    }
                }
            }}
        </div>
    }
}

/// Data Model has no tool to offer, unlike Code Graph and Slop Detection, so
/// its empty state cannot be "install this and press run".
///
/// It says where the file goes, what writes it, and what it looks like. An
/// empty state whose only content is "no data registered" restates what the
/// reader is already looking at and leaves them at a dead end -- which is
/// exactly how the enrichment empty states failed before they were rebuilt.
#[component]
fn DataModelEmptyState() -> impl IntoView {
    view! {
        <div class="data-model-panel__empty">
            <span class="overline">"DATA MODEL"</span>
            <h3>"No persistence model recorded"</h3>
            <p>
                "Unlike Code Graph and Slop Detection, this view is not generated by a
                 tool. " <code>"entities.json"</code>
                " is authored, the same way nodes and flows are, and describes the
                 entities your system stores: their attributes, keys, and relationships."
            </p>
            <p class="data-model-panel__empty-step">
                "1. Create " <code>"docs/architext/data/entities.json"</code>
                " and register it as " <code>"manifest.files.entities"</code>
                ". " <code>"architext doctor --yes"</code> " registers it for you."
            </p>
            <p class="data-model-panel__empty-step">
                "2. Describe each entity. An agent can draft this from your migrations
                 or ORM models; the source-extraction contract asks for a reviewable
                 draft with source paths before the data file is edited."
            </p>
            <pre class="data-model-panel__example">
r#"{
  "entities": [
    {
      "id": "release",
      "name": "Release",
      "ownerNodeId": "release-store",
      "attributes": [
        { "name": "id", "type": "uuid", "key": "primary" },
        { "name": "plan_id", "type": "uuid", "key": "foreign",
          "references": "plan" }
      ],
      "relationships": [
        { "to": "release_item", "cardinality": "one-to-many",
          "label": "contains" }
      ]
    }
  ]
}"#
            </pre>
            <p class="data-model-panel__empty-step">
                "3. Run " <code>"architext validate"</code>
                ". Every relationship and foreign key must name an entity that exists."
            </p>
        </div>
    }
}

#[component]
fn ErDiagram(plan: ErPlan) -> impl IntoView {
    let view_box = format!("0 0 {} {}", plan.canvas_width, plan.canvas_height);
    let edges: Vec<ErEdge> = plan.edges.clone();
    let boxes: Vec<ErBox> = plan.boxes.clone();

    view! {
        <div class="data-model-panel__canvas">
            <svg
                class="er-diagram"
                viewBox=view_box
                width=plan.canvas_width
                height=plan.canvas_height
                xmlns="http://www.w3.org/2000/svg"
            >
                <g class="er-diagram__edges">
                    {edges
                        .into_iter()
                        .map(|e| {
                            let d = path_d(&e.points);
                            let feet = foot_paths(&e);
                            let label = e.label.clone();
                            view! {
                                <g class="er-edge">
                                    <path class="er-edge__line" d=d/>
                                    {feet
                                        .into_iter()
                                        .map(|fd| view! { <path class="er-edge__foot" d=fd/> })
                                        .collect_view()}
                                    {label
                                        .map(|text| {
                                            view! {
                                                <text
                                                    class="er-edge__label"
                                                    x=e.label_x
                                                    y=e.label_y
                                                    text-anchor="middle"
                                                >
                                                    {text}
                                                </text>
                                            }
                                        })}
                                </g>
                            }
                        })
                        .collect_view()}
                </g>
                <g class="er-diagram__boxes">
                    {boxes.into_iter().map(|b| view! { <EntityBox entity=b/> }).collect_view()}
                </g>
            </svg>
        </div>
    }
}

#[component]
fn EntityBox(entity: ErBox) -> impl IntoView {
    let rows_top = entity.y + HEADER_H + BOX_PAD_Y;
    let x_text = entity.x + 10.0;
    let header_baseline = entity.y + HEADER_H - 8.0;

    view! {
        <g class="er-box">
            <rect
                class="er-box__frame"
                x=entity.x
                y=entity.y
                width=entity.width
                height=entity.height
                rx="4"
            />
            <rect
                class="er-box__header"
                x=entity.x
                y=entity.y
                width=entity.width
                height=HEADER_H
            />
            <text class="er-box__name" x=x_text y=header_baseline>
                {entity.name.clone()}
            </text>
            {entity
                .rows
                .iter()
                .enumerate()
                .map(|(i, row)| {
                    // Baseline sits just above the row's bottom edge so glyph
                    // descenders stay inside the row band.
                    let y = rows_top + (i as f64) * ROW_H + ROW_H - 4.0;
                    let annotation = fk_annotation(row);
                    let unresolved = annotation
                        .as_deref()
                        .is_some_and(|a| a.ends_with("(no relationship declared)"));
                    let label = match annotation {
                        Some(a) => format!("{}  {}  \u{2192} {}", row.name, row.type_name, a),
                        None => format!("{}  {}", row.name, row.type_name),
                    };
                    view! {
                        <g class="er-row" class:is-unresolved=unresolved>
                            <text class="er-row__key" x=x_text y=y>
                                {key_glyph(row.key.as_deref())}
                            </text>
                            <text class="er-row__text" x=x_text + 22.0 y=y>
                                {label}
                            </text>
                        </g>
                    }
                })
                .collect_view()}
        </g>
    }
}

/// Orthogonal polyline as an SVG path.
fn path_d(points: &[Point]) -> String {
    let mut d = String::new();
    for (i, p) in points.iter().enumerate() {
        if i == 0 {
            d.push_str(&format!("M{} {}", p.x, p.y));
        } else {
            d.push_str(&format!(" L{} {}", p.x, p.y));
        }
    }
    d
}

/// The crow's-foot (or single tick) drawn at each end of an edge.
///
/// Direction comes from the adjoining segment, so a foot always points back
/// along the line it terminates rather than assuming a fixed orientation.
fn foot_paths(edge: &ErEdge) -> Vec<String> {
    let pts = &edge.points;
    if pts.len() < 2 {
        return Vec::new();
    }
    let mut out = Vec::new();
    out.extend(foot_at(&pts[0], &pts[1], edge.from_foot));
    let n = pts.len();
    out.extend(foot_at(&pts[n - 1], &pts[n - 2], edge.to_foot));
    out
}

/// `tip` is the endpoint; `toward` is the next point along the edge, which
/// gives the inward direction.
fn foot_at(tip: &Point, toward: &Point, foot: ErFoot) -> Vec<String> {
    let (dx, dy) = (toward.x - tip.x, toward.y - tip.y);
    let len = (dx * dx + dy * dy).sqrt();
    if len < f64::EPSILON {
        return Vec::new();
    }
    let (ux, uy) = (dx / len, dy / len); // inward unit vector
    let (px, py) = (-uy, ux); // perpendicular

    match foot {
        // "one": a single bar across the line, set back from the tip.
        ErFoot::One => {
            let cx = tip.x + ux * FOOT_LEN;
            let cy = tip.y + uy * FOOT_LEN;
            vec![format!(
                "M{} {} L{} {}",
                cx - px * FOOT_SPREAD,
                cy - py * FOOT_SPREAD,
                cx + px * FOOT_SPREAD,
                cy + py * FOOT_SPREAD
            )]
        }
        // "many": three prongs meeting at the tip.
        ErFoot::Many => {
            let bx = tip.x + ux * FOOT_LEN;
            let by = tip.y + uy * FOOT_LEN;
            vec![
                format!("M{} {} L{} {}", tip.x, tip.y, bx, by),
                format!(
                    "M{} {} L{} {}",
                    tip.x,
                    tip.y,
                    bx + px * FOOT_SPREAD,
                    by + py * FOOT_SPREAD
                ),
                format!(
                    "M{} {} L{} {}",
                    tip.x,
                    tip.y,
                    bx - px * FOOT_SPREAD,
                    by - py * FOOT_SPREAD
                ),
            ]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_many_foot_draws_three_prongs_and_a_one_foot_draws_one_bar() {
        // WHY: cardinality is one of the few pinned vocabularies precisely
        // because the renderer draws a specific glyph per value. If both feet
        // render the same, the pin is buying nothing.
        let tip = Point { x: 0.0, y: 0.0 };
        let toward = Point { x: 10.0, y: 0.0 };
        assert_eq!(foot_at(&tip, &toward, ErFoot::Many).len(), 3);
        assert_eq!(foot_at(&tip, &toward, ErFoot::One).len(), 1);
    }

    #[test]
    fn a_degenerate_segment_draws_no_foot() {
        // Two identical points give no direction; dividing by that length would
        // put NaN into the path and silently blank the edge.
        let p = Point { x: 5.0, y: 5.0 };
        assert!(foot_at(&p, &p, ErFoot::Many).is_empty());
    }

    #[test]
    fn path_d_emits_a_move_then_lines() {
        let d = path_d(&[
            Point { x: 0.0, y: 0.0 },
            Point { x: 10.0, y: 0.0 },
            Point { x: 10.0, y: 5.0 },
        ]);
        assert_eq!(d, "M0 0 L10 0 L10 5");
    }
}
