//! Data Model mode: the Schema projection of `entities.json`, drawn as SVG.
//!
//! Real SVG rather than a canvas, so the text stays selectable, CSS theming
//! applies, and the browser's own print path (which is what the PDF button
//! drives) renders the diagram as page content.

use leptos::*;

use architext_routing::model::Point;
use architext_routing::plan_er::{
    plan_er, route_edges, ErBox, ErEdge, ErFoot, ErInput, BOX_PAD_X, BOX_PAD_Y, CHAR_W, HEADER_H,
    ROW_H, ROW_TEXT_X,
};

use crate::data_model_view_model::{
    fk_annotation, fk_tooltip, key_glyph, to_er_input, Projection,
};
use crate::state::use_app_state;

/// Length of the tick/prong drawn at an edge endpoint.
const FOOT_LEN: f64 = 9.0;
/// Half-height of the crow's-foot spread.
const FOOT_SPREAD: f64 = 5.0;
/// Radius of the little bridge drawn where one line crosses another.
const HOP_R: f64 = 5.0;
/// Padding inside a relationship label's pill.
const PILL_PAD_X: f64 = 6.0;
const PILL_H: f64 = 15.0;

#[component]
pub fn DataModelPanel() -> impl IntoView {
    let state = use_app_state();
    let (projection, set_projection) = create_signal(Projection::Schema);

    let doc = move || state.data.get().entities.as_ref().and_then(|r| r.as_ref().ok().cloned());
    let error =
        move || state.data.get().entities.as_ref().and_then(|r| r.as_ref().err().map(|e| e.to_string()));

    view! {
        <div class="data-model-panel">
            <div class="data-model-panel__projections" role="tablist" aria-label="Projection">
                {Projection::ALL
                    .iter()
                    .map(|p| {
                        let p = *p;
                        view! {
                            <button
                                class="data-model-panel__projection"
                                class:is-active=move || projection.get() == p
                                role="tab"
                                disabled=!p.available()
                                title=p.unavailable_reason().unwrap_or("")
                                aria-selected=move || (projection.get() == p).to_string()
                                on:click=move |_| {
                                    if p.available() {
                                        set_projection.set(p);
                                    }
                                }
                            >
                                {p.label()}
                            </button>
                        }
                    })
                    .collect_view()}
            </div>

            {move || {
                if let Some(err) = error() {
                    return view! {
                        <div class="data-model-panel__empty">
                            <span class="overline">"DATA MODEL"</span>
                            <p>{err}</p>
                        </div>
                    }
                        .into_view();
                }
                match doc() {
                    None => view! { <DataModelEmptyState/> }.into_view(),
                    Some(d) if d.entities.is_empty() => {
                        view! { <DataModelEmptyState/> }.into_view()
                    }
                    Some(d) => {
                        let input = to_er_input(&d);
                        let plan = plan_er(&input);
                        view! { <ErDiagram plan=plan input=input/> }.into_view()
                    }
                }
            }}
        </div>
    }
}

/// Data Model has no tool to offer, unlike Code Graph and Slop Detection, so
/// its empty state cannot be "install this and press run".
///
/// It says where the file goes, what writes it, and what it looks like. An
/// empty state whose only content is "no data registered" restates what the
/// reader is already looking at and leaves them at a dead end -- which is
/// exactly how the enrichment empty states failed before they were rebuilt.
#[component]
fn DataModelEmptyState() -> impl IntoView {
    view! {
        <div class="data-model-panel__empty">
            <span class="overline">"DATA MODEL"</span>
            <h3>"No persistence model recorded"</h3>
            <p>
                "Unlike Code Graph and Slop Detection, this view is not generated by a
                 tool. " <code>"entities.json"</code>
                " is authored, the same way nodes and flows are, and describes the
                 entities your system stores: their attributes, keys, and relationships."
            </p>
            <p class="data-model-panel__empty-step">
                "1. Create " <code>"docs/architext/data/entities.json"</code>
                " and register it as " <code>"manifest.files.entities"</code>
                ". " <code>"architext doctor --yes"</code> " registers it for you."
            </p>
            <p class="data-model-panel__empty-step">
                "2. Describe each entity. An agent can draft this from your migrations
                 or ORM models; the source-extraction contract asks for a reviewable
                 draft with source paths before the data file is edited."
            </p>
            <pre class="data-model-panel__example">
r#"{
  "entities": [
    {
      "id": "release",
      "name": "Release",
      "ownerNodeId": "release-store",
      "attributes": [
        { "name": "id", "type": "uuid", "key": "primary" },
        { "name": "plan_id", "type": "uuid", "key": "foreign",
          "references": "plan" }
      ],
      "relationships": [
        { "to": "release_item", "cardinality": "one-to-many",
          "label": "contains" }
      ]
    }
  ]
}"#
            </pre>
            <p class="data-model-panel__empty-step">
                "3. Run " <code>"architext validate"</code>
                ". Every relationship and foreign key must name an entity that exists."
            </p>
        </div>
    }
}

#[component]
fn ErDiagram(plan: architext_routing::plan_er::ErPlan, input: ErInput) -> impl IntoView {
    // Boxes and edges are STATE, not fixed props, because entities can be
    // dragged. Edges are rebuilt through `route_edges` on every move rather
    // than nudged, so a dragged box re-picks which face each line leaves from,
    // redistributes the ports on it, and recomputes hops -- the same code the
    // initial layout used, so a dragged diagram cannot drift from a planned one.
    let (boxes, set_boxes) = create_signal(plan.boxes.clone());
    let (edges, set_edges) = create_signal(plan.edges.clone());
    // (index, pointer-to-box offset)
    let drag = store_value(None::<(usize, f64, f64)>);
    let svg_ref = create_node_ref::<leptos::svg::Svg>();
    let input = store_value(input);

    let canvas_w = plan.canvas_width;
    let canvas_h = plan.canvas_height;
    let view_box = format!("0 0 {canvas_w} {canvas_h}");

    let pointer_pos = move |ev: &web_sys::PointerEvent| -> Option<(f64, f64)> {
        let el = svg_ref.get()?;
        let rect = el.get_bounding_client_rect();
        Some((ev.client_x() as f64 - rect.left(), ev.client_y() as f64 - rect.top()))
    };

    let on_move = move |ev: web_sys::PointerEvent| {
        let Some((idx, ox, oy)) = drag.get_value() else { return };
        let Some((x, y)) = pointer_pos(&ev) else { return };
        set_boxes.update(|bs| {
            if let Some(b) = bs.get_mut(idx) {
                // Clamped to the canvas so a box cannot be dragged out of the
                // scrollable area and become unreachable.
                b.x = (x - ox).clamp(0.0, (canvas_w - b.width).max(0.0));
                b.y = (y - oy).clamp(0.0, (canvas_h - b.height).max(0.0));
            }
        });
        set_edges.set(route_edges(&boxes.get_untracked(), &input.get_value()));
    };
    let on_up = move |_ev: web_sys::PointerEvent| drag.set_value(None);

    view! {
        <div class="data-model-panel__canvas">
            <svg
                node_ref=svg_ref
                class="er-diagram"
                class:is-dragging=move || drag.with_value(|d| d.is_some())
                viewBox=view_box
                width=canvas_w
                height=canvas_h
                xmlns="http://www.w3.org/2000/svg"
                on:pointermove=on_move
                on:pointerup=on_up
                on:pointerleave=on_up
            >
                <g class="er-diagram__edges">
                    {move || {
                        edges
                            .get()
                            .into_iter()
                            .map(|e| {
                                let d = path_with_hops(&e);
                                let feet = foot_paths(&e);
                                let label = e.label.clone();
                                let (lx, ly) = (e.label_x, e.label_y);
                                view! {
                                    <g class="er-edge">
                                        <path class="er-edge__line" d=d/>
                                        {feet
                                            .into_iter()
                                            .map(|fd| view! { <path class="er-edge__foot" d=fd/> })
                                            .collect_view()}
                                        {label
                                            .map(|text| {
                                                // A pill behind the text, so a
                                                // label crossing a line stays
                                                // readable instead of tangling
                                                // with it.
                                                let w = text.chars().count() as f64 * CHAR_W
                                                    + PILL_PAD_X * 2.0;
                                                view! {
                                                    <g class="er-edge__label-group">
                                                        <rect
                                                            class="er-edge__label-pill"
                                                            x=lx - w / 2.0
                                                            y=ly - PILL_H / 2.0
                                                            width=w
                                                            height=PILL_H
                                                            rx=PILL_H / 2.0
                                                        />
                                                        <text
                                                            class="er-edge__label"
                                                            x=lx
                                                            y=ly + 3.5
                                                            text-anchor="middle"
                                                        >
                                                            {text}
                                                        </text>
                                                    </g>
                                                }
                                            })}
                                    </g>
                                }
                            })
                            .collect_view()
                    }}
                </g>
                <g class="er-diagram__boxes">
                    {move || {
                        boxes
                            .get()
                            .into_iter()
                            .enumerate()
                            .map(|(i, b)| {
                                let on_down = move |ev: web_sys::PointerEvent| {
                                    if let Some(el) = svg_ref.get() {
                                        let rect = el.get_bounding_client_rect();
                                        let (x, y) = (
                                            ev.client_x() as f64 - rect.left(),
                                            ev.client_y() as f64 - rect.top(),
                                        );
                                        let b = &boxes.get_untracked()[i];
                                        drag.set_value(Some((i, x - b.x, y - b.y)));
                                    }
                                    ev.prevent_default();
                                };
                                view! { <EntityBox entity=b on_pointer_down=on_down/> }
                            })
                            .collect_view()
                    }}
                </g>
            </svg>
        </div>
    }
}

#[component]
fn EntityBox(
    entity: ErBox,
    #[prop(into)] on_pointer_down: Callback<web_sys::PointerEvent>,
) -> impl IntoView {
    let rows_top = entity.y + HEADER_H + BOX_PAD_Y;
    let x_text = entity.x + 10.0;
    let header_baseline = entity.y + HEADER_H - 8.0;

    view! {
        <g class="er-box" on:pointerdown=move |ev| on_pointer_down.call(ev)>
            <rect
                class="er-box__frame"
                x=entity.x
                y=entity.y
                width=entity.width
                height=entity.height
                rx="4"
            />
            <rect
                class="er-box__header"
                x=entity.x
                y=entity.y
                width=entity.width
                height=HEADER_H
            />
            <text class="er-box__name" x=x_text y=header_baseline>
                {entity.name.clone()}
            </text>
            {entity
                .rows
                .iter()
                .enumerate()
                .map(|(i, row)| {
                    // Baseline sits just above the row's bottom edge so glyph
                    // descenders stay inside the row band.
                    let y = rows_top + (i as f64) * ROW_H + ROW_H - 4.0;
                    let annotation = fk_annotation(row);
                    let tooltip = fk_tooltip(row);
                    let unresolved = tooltip.is_some();
                    let label = match annotation {
                        Some(a) => format!("{}  {}  \u{2192} {}", row.name, row.type_name, a),
                        None => format!("{}  {}", row.name, row.type_name),
                    };
                    let label = truncate_to_box(&label, entity.width);
                    view! {
                        <g class="er-row" class:is-unresolved=unresolved>
                            {tooltip.map(|t| view! { <title>{t}</title> })}
                            <text class="er-row__key" x=x_text y=y>
                                {key_glyph(row.key.as_deref())}
                            </text>
                            <text class="er-row__text" x=x_text + 22.0 y=y>
                                {label}
                            </text>
                        </g>
                    }
                })
                .collect_view()}
        </g>
    }
}

/// Clip a row's text to the width the layout allocated.
///
/// Box width comes from an ESTIMATE (layout runs in WASM with no font metrics
/// and must match native byte for byte), and it is clamped to a maximum. Either
/// can leave a row wider than its box, which renders as text running out of one
/// entity and across the next. Truncating here makes that structurally
/// impossible for any content, rather than merely unlikely for this fixture.
fn truncate_to_box(text: &str, box_width: f64) -> String {
    let usable = box_width - ROW_TEXT_X - BOX_PAD_X;
    // The epsilon matters: box width is computed as `n * CHAR_W`, so dividing it
    // back by CHAR_W lands a hair under `n` in binary floating point (191.4/6.6
    // = 28.999...). Without it, `floor` truncates a row that fits EXACTLY --
    // which is every row that determined its own box's width.
    let max_chars = (usable / CHAR_W + 1e-6).floor().max(1.0) as usize;
    if text.chars().count() <= max_chars {
        return text.to_string();
    }
    let kept: String = text.chars().take(max_chars.saturating_sub(1)).collect();
    format!("{kept}\u{2026}")
}

/// The edge as an SVG path, bridging over every line it crosses.
///
/// Two lines meeting at a point are ambiguous -- a reader cannot tell a
/// crossing from a join. A small arc at each crossing says "over", which is the
/// convention every schematic uses and costs nothing to draw.
fn path_with_hops(edge: &ErEdge) -> String {
    let (a, b) = (&edge.points[0], &edge.points[edge.points.len() - 1]);
    let (dx, dy) = (b.x - a.x, b.y - a.y);
    let len = (dx * dx + dy * dy).sqrt();
    if len < 1e-9 || edge.hops.is_empty() {
        return path_d(&edge.points);
    }
    let (ux, uy) = (dx / len, dy / len);
    let mut d = format!("M{} {}", a.x, a.y);
    for h in &edge.hops {
        let (bx, by) = (h.x - ux * HOP_R, h.y - uy * HOP_R);
        let (ax, ay) = (h.x + ux * HOP_R, h.y + uy * HOP_R);
        // Sweep 1 keeps every bridge bowing the same way along the line.
        d.push_str(&format!(
            " L{bx} {by} A{HOP_R} {HOP_R} 0 0 1 {ax} {ay}"
        ));
    }
    d.push_str(&format!(" L{} {}", b.x, b.y));
    d
}

/// Polyline as an SVG path.
fn path_d(points: &[Point]) -> String {
    let mut d = String::new();
    for (i, p) in points.iter().enumerate() {
        if i == 0 {
            d.push_str(&format!("M{} {}", p.x, p.y));
        } else {
            d.push_str(&format!(" L{} {}", p.x, p.y));
        }
    }
    d
}

/// The crow's-foot (or single tick) drawn at each end of an edge.
///
/// Direction comes from the adjoining segment, so a foot always points back
/// along the line it terminates rather than assuming a fixed orientation.
fn foot_paths(edge: &ErEdge) -> Vec<String> {
    let pts = &edge.points;
    if pts.len() < 2 {
        return Vec::new();
    }
    let mut out = Vec::new();
    out.extend(foot_at(&pts[0], &pts[1], edge.from_foot));
    let n = pts.len();
    out.extend(foot_at(&pts[n - 1], &pts[n - 2], edge.to_foot));
    out
}

/// `tip` is the endpoint; `toward` is the next point along the edge, which
/// gives the inward direction.
fn foot_at(tip: &Point, toward: &Point, foot: ErFoot) -> Vec<String> {
    let (dx, dy) = (toward.x - tip.x, toward.y - tip.y);
    let len = (dx * dx + dy * dy).sqrt();
    if len < f64::EPSILON {
        return Vec::new();
    }
    let (ux, uy) = (dx / len, dy / len); // inward unit vector
    let (px, py) = (-uy, ux); // perpendicular

    match foot {
        // "one": a single bar across the line, set back from the tip.
        ErFoot::One => {
            let cx = tip.x + ux * FOOT_LEN;
            let cy = tip.y + uy * FOOT_LEN;
            vec![format!(
                "M{} {} L{} {}",
                cx - px * FOOT_SPREAD,
                cy - py * FOOT_SPREAD,
                cx + px * FOOT_SPREAD,
                cy + py * FOOT_SPREAD
            )]
        }
        // "many": three prongs meeting at the tip.
        ErFoot::Many => {
            let bx = tip.x + ux * FOOT_LEN;
            let by = tip.y + uy * FOOT_LEN;
            vec![
                format!("M{} {} L{} {}", tip.x, tip.y, bx, by),
                format!(
                    "M{} {} L{} {}",
                    tip.x,
                    tip.y,
                    bx + px * FOOT_SPREAD,
                    by + py * FOOT_SPREAD
                ),
                format!(
                    "M{} {} L{} {}",
                    tip.x,
                    tip.y,
                    bx - px * FOOT_SPREAD,
                    by - py * FOOT_SPREAD
                ),
            ]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_many_foot_draws_three_prongs_and_a_one_foot_draws_one_bar() {
        // WHY: cardinality is one of the few pinned vocabularies precisely
        // because the renderer draws a specific glyph per value. If both feet
        // render the same, the pin is buying nothing.
        let tip = Point { x: 0.0, y: 0.0 };
        let toward = Point { x: 10.0, y: 0.0 };
        assert_eq!(foot_at(&tip, &toward, ErFoot::Many).len(), 3);
        assert_eq!(foot_at(&tip, &toward, ErFoot::One).len(), 1);
    }

    #[test]
    fn a_degenerate_segment_draws_no_foot() {
        // Two identical points give no direction; dividing by that length would
        // put NaN into the path and silently blank the edge.
        let p = Point { x: 5.0, y: 5.0 };
        assert!(foot_at(&p, &p, ErFoot::Many).is_empty());
    }

    #[test]
    fn a_row_wider_than_its_box_is_truncated() {
        // The layout estimates text width and clamps box width, so a row CAN
        // exceed its box. Unclipped, it renders across the neighbouring entity
        // -- which is exactly what a 153px overflow looked like on screen.
        let long = "parent_id  uuid  \u{2192} category (not drawn)";
        let clipped = truncate_to_box(long, 120.0);
        assert!(clipped.ends_with('\u{2026}'), "expected an ellipsis, got {clipped:?}");
        assert!(clipped.chars().count() < long.chars().count());
        // and a row that fits is left exactly alone
        assert_eq!(truncate_to_box("id  uuid", 320.0), "id  uuid");

        // A row that fits EXACTLY must survive. This is the case floating point
        // got wrong: a box sized to n characters divided back to 28.999..., so
        // the row that set the box's own width was the one clipped.
        let n = 29;
        let exact: String = "x".repeat(n);
        let width = ROW_TEXT_X + n as f64 * CHAR_W + BOX_PAD_X;
        assert_eq!(truncate_to_box(&exact, width), exact, "an exactly-fitting row must not clip");
    }

    #[test]
    fn a_crossing_draws_a_bridge_and_a_clear_line_does_not() {
        // WHY: two lines meeting at a point read as a join. The arc is what
        // says "over". A hop list that stopped reaching the path would silently
        // return the diagram to ambiguous crossings.
        let mk = |hops: Vec<Point>| ErEdge {
            from: "a".into(),
            to: "b".into(),
            label: None,
            cardinality: "one-to-one".into(),
            points: vec![Point { x: 0.0, y: 0.0 }, Point { x: 100.0, y: 0.0 }],
            from_foot: ErFoot::One,
            to_foot: ErFoot::One,
            label_x: 50.0,
            label_y: 0.0,
            hops,
        };
        let clear = path_with_hops(&mk(Vec::new()));
        assert!(!clear.contains('A'), "no crossings, so no arc: {clear}");

        let bridged = path_with_hops(&mk(vec![Point { x: 50.0, y: 0.0 }]));
        assert!(bridged.contains('A'), "a crossing must draw an arc: {bridged}");
        // Approaches the crossing, bridges it, then carries on to the end.
        assert!(bridged.starts_with("M0 0"));
        assert!(bridged.ends_with("L100 0"));
    }

    #[test]
    fn path_d_emits_a_move_then_lines() {
        let d = path_d(&[
            Point { x: 0.0, y: 0.0 },
            Point { x: 10.0, y: 0.0 },
            Point { x: 10.0, y: 5.0 },
        ]);
        assert_eq!(d, "M0 0 L10 0 L10 5");
    }
}
